# Generated by Django 5.1.1 on 2025-02-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], default='article', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('assigned', 'Assigned')], default='private', max_length=10),
        ),
    ]
