# Generated by Django 5.1.1 on 2025-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_answer_studentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='courses',
            field=models.ManyToManyField(related_name='resources', to='main.course'),
        ),
    ]
